### ISSUE TITLE
Turn off frames

### ISSUE THREAD

**Issue by zzak** [mruby/mruby.github.io#38]
It seems like mruby.org is running inside a frame, but I don't know enough about how the template is generated to be able to fix it. I _think_ it's generated using [yard-mruby](https://github.com/sagmor/yard-mruby).

For example:

1. Go to mruby.org/
2. Click any link.
3. The address bar still says mruby.org

I think we should avoid using frames if possible.

/cc @sagmor @Mav7

**Comment by Mav7** [comment]
I was wondering about that too. I'm currently looking into it; interestingly enough when I run the site locally It isn't an issue.

**Comment by Mav7** [comment]
When I run the site locally It isn't an issue. However when I click on **no frames** all of a sudden the problem goes away. A file called **frames.html** gets generated it looks like that might be part of the problem. What do you think? @sagmor

**Comment by sagmor** [comment]
I see,

mruby.org's template is inside a frame (no idea why) but it's effectively messing with YARD's template.
The template itself detect's it's inside a frame and hides all it's navigation (asumes it's inside YARD's framed view)

There are two possible solutions.
* Remove the frame from mruby.org
* Add a `target="_top"` to the api doc link (so it's loaded on a frame free page)

**Comment by strcmp** [comment]
i think removing the frame is the way to go, although i dont have much experience with it. i know default yard(at least from few years ago) supported a frame and non-framed version, but i cannot see any yardoc options that would change that to always use the version without frames. i think generally frames are not what you want, so could be good to remove them, maybe.

**Comment by strcmp** [comment]
i think for seo purposes frames could be bad, even with _target= trick.

**Comment by sagmor** [comment]
Found the issue!

It's a DNS/Server issue.

This website is configured with the [www.mruby.org CNAME](https://github.com/mruby/mruby.github.io/blob/e5d73532de5d4be7c51d57d899500a1a9ec24fe3/CNAME) so if you navigate to http://www.mruby.org you see the website without frames in it's full glory.

But if you go to http://mruby.org you actually get this back:
```
curl http://mruby.org/
<HTML>
<HEAD>
        <TITLE>
	</TITLE>
	<META NAME='keywords' CONTENT=''>
	<META HTTP-EQUIV="Content-Type" content="text/html; charset=UTF-8">
</HEAD>

<FRAMESET ROWS="100%,*">
        <FRAME SRC="http://mruby.github.io" NAME="main">
</FRAMESET>

<NOFRAMES>
Sorry, your browser does not support frames.  Please <A HREF="http://mruby.github.io" TARGET=_top>go here</A>
</NOFRAMES>

</HTML>
```

So somebody has to change mruby.org DNS so that it redirects instead of loading the site in a frame

**Comment by strcmp** [comment]
cool. i think that is also bad for seo purposes, mruby.org is essentially acting as a duplicate of www.mruby.org

**Comment by zzak** [comment]
@matz Can you please fix the DNS for mruby.org to www?

**Comment by matz** [comment]
I don't know how to fix. the tool currently using does not allow cname from `mruby.org`. maybe we have to change our name server.

**Comment by zzak** [comment]
@matz CNAME is not allowed for bare domain, so we have to setup a redirect for http://mruby.org -> http://www.mruby.org

**Comment by matz** [comment]
hmm, how can I redirect using github.io?

**Comment by zzak** [comment]
@matz I think you have to make the change on the DNS provider

**Comment by matz** [comment]
I don't know how to solve the issue. Sorry for my ignorance.

**Comment by zzak** [comment]
As a work-around, we could do an HTTP redirect using JavaScript or HTML.

I'm not sure what the best solution is.

**Comment by strcmp** [comment]
i think the best way would be a 301 redirect: https://support.google.com/webmasters/answer/93633?hl=en
i dont think html or javascript redirects are counted by that particular robot, it expects to make a GET and see a 301 to www.mruby.org. page rank and everything else is then eventually transferred to www.mruby.org. for example:
```
curl -I https://www.github.com
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://github.com/
Connection: close
```
in context of github pages im not sure how that works. i usually use .htaccess or similar. rack middleware could also do it.

**Comment by sagmor** [comment]
May I suggest moving mruby.org DNS to [Cloudflare](http://cloudflare.com/)?
It handles CNAMES at the top and you get HTTPs and CDN for free ;)

The setup is also pretty easy and works great with github pages.
I can help with the setup if needed.

**Comment by strcmp** [comment]
besides the issue of framed content, if you serve http://mruby.org and http://www.ruby.org as 200 OK then google will see those two sites as not one as the same but as different websites. google considers all variations of this to be different websites: https://github.com, https://www.github.com, and https://foo.github.com.

when content is duplicated on different websites, you are less likely to rank highly in search results and page rank will be distributed across two websites instead of one. one way to solve this issue without a redirect would be to use `<link>` tags instead, for example:
```html
<link rel="canonical" href="https://www.mruby.org">
```
and href should be updated to reflect the current path on each page, this would tell robots that these two pages are the same(mruby.org and www.mruby.org), so you wouldn't run into the duplicated content issue. 

not sure what the path to follow is, and i guess they are two separate problems to solve (frames vs seo).

**Comment by sagmor** [comment]
In terms of SEO, as far as I know the best solution is to pick a single domain (either mruby.org or www.mruby.org) and redirect all the content from one to the other with a 301 Moved Permanently.

**Comment by strcmp** [comment]
indeed, that would be the best solution.

**Comment by matz** [comment]
I signed in to cloudflare and made it a name server for mruby.org.

**Comment by zzak** [comment]
LGTM, thanks @matz

**Comment by strcmp** [comment]
:clap:

**Comment by Hir0** [comment]
Matz-san MX record of mruby.org has been changed at new DNS. PLS  change host name to mail.mruby.org

**Comment by matz** [comment]
@Hir0 It was using CloudFlare's CDN. Sorry.

**Comment by Hir0** [comment]
Mail problem was fixed,Thanks @matz
